id: galaxy

events:
  - type: title
    title: "Galaxy recebida!"
    subtitle: "{viewer} iniciou o caos"

  - type: sound
    sound: ENTITY_WITHER_SPAWN
    delay: 10

  - type: lightning
    amount: 5
    delay: 20

  - type: tnt
    amount: 20
    delay: 40